Object Detection DPC Globals
Object Detection DPC Globals
Object Detection DPC (Data-path Processing Chain) External
This section has a list of all the globals exposed by the Object detection DPC.
Functions
static void DPC_ObjDetRangeHwa_MemPoolReset (MemPoolObj *pool)
static uint32_t DPC_ObjDetRangeHwa_MemPoolGetMaxUsage (MemPoolObj *pool)
static void * DPC_ObjDetRangeHwa_MemPoolAlloc (MemPoolObj *pool, uint32_t size, uint8_t align)
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char *file, int32_t line)
Variables
DPM_ProcChainCfg gDPC_ObjDetRangeHWACfg
Global used to register Object Detection DPC in DPM.
DPM_ProcChainCfg gDPC_ObjDetRangeHWACfg
Global used to register Object Detection DPC in DPM.
Detailed Description
This section has a list of all the globals exposed by the Object detection DPC.
Function Documentation
_DPC_Objdet_Assert()
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char * file, int32_t line)
Description
Sends Assert
Return values
Not Applicable.
Definition at line 235 of file objdetrangehwa.c.
References DPM_DPCAssert_t::arg0, DPM_DPCAssert_t::arg1, DPM_CMD_DPC_ASSERT, DPM_ioctl(), DPM_MAX_FILE_NAME_LEN, DPM_DPCAssert_t::fileName, and DPM_DPCAssert_t::lineNum.
DPC_ObjDetRangeHwa_MemPoolAlloc()
static void* DPC_ObjDetRangeHwa_MemPoolAlloc (MemPoolObj * pool, uint32_t size, uint8_t align) static
Description
Utility function for allocating from a static memory pool.
Parameters
[in] pool Handle to pool object.
[in] size Size in bytes to be allocated.
[in] align Alignment in bytes
Return values
pointer to beginning of allocated block. NULL indicates could not allocate.
Definition at line 208 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, MemPoolObj_t::maxCurrAddr, and DPC_ObjectDetectionRangeHWA_MemCfg_t::size.
Referenced by DPC_ObjDetRangeHwa_preStartConfig(), and DPC_ObjDetRangeHwa_rangeConfig().
DPC_ObjDetRangeHwa_MemPoolGetMaxUsage()
static uint32_t DPC_ObjDetRangeHwa_MemPoolGetMaxUsage (MemPoolObj * pool) static
Description
Utility function for getting maximum memory pool usage.
Parameters
[in] pool Handle to pool object.
Return values
Amount of pool used in bytes.
Definition at line 188 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetRangeHwa_preStartConfig().
DPC_ObjDetRangeHwa_MemPoolReset()
static void DPC_ObjDetRangeHwa_MemPoolReset (MemPoolObj * pool) static
Description
Utility function for reseting memory pool.
Parameters
[in] pool Handle to pool object.
Return values
none.
Definition at line 169 of file objdetrangehwa.c.
References DPC_ObjectDetectionRangeHWA_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetRangeHwa_preStartConfig().
Variable Documentation
gDPC_ObjDetRangeHWACfg [1/2]
DPM_ProcChainCfg gDPC_ObjDetRangeHWACfg extern
Global used to register Object Detection DPC in DPM.
Application developers: Use this configuration to load the Object Detection DPC within the DPM.
Definition at line 142 of file objdetrangehwa.c.
gDPC_ObjDetRangeHWACfg [2/2]
DPM_ProcChainCfg gDPC_ObjDetRangeHWACfg
Initial value:
=
{
    DPC_ObjectDetection_init,
    DPC_ObjectDetection_start,
    DPC_ObjectDetection_execute,
    DPC_ObjectDetection_ioctl,
    DPC_ObjectDetection_stop,
    DPC_ObjectDetection_deinit,
    NULL,
    NULL,
    DPC_ObjectDetection_frameStart
}
Global used to register Object Detection DPC in DPM.
Application developers: Use this configuration to load the Object Detection DPC within the DPM.
Definition at line 142 of file objdetrangehwa.c.
Copyright 2024, Texas Instruments Incorporated