Object Detection DPC Internal Functions
Object Detection DPC Internal Functions
Object Detection DPC (Data Path Chain) Internal
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Functions
static void DPC_ObjDetDSP_MemPoolReset (MemPoolObj *pool)
static void DPC_ObjDetDSP_MemPoolSet (MemPoolObj *pool, void *addr)
static void * DPC_ObjDetDSP_MemPoolGet (MemPoolObj *pool)
static uint32_t DPC_ObjDetDSP_MemPoolGetMaxUsage (MemPoolObj *pool)
static void * DPC_ObjDetDSP_MemPoolAlloc (MemPoolObj *pool, uint32_t size, uint8_t align)
void DPC_ObjectDetection_chirpEvent (DPM_DPCHandle handle)
static uint32_t DPC_ObjDetDSP_GetRangeWinGenLen (uint16_t numAdcSamples)
static void DPC_ObjDetDSP_GenRangeWindow (DPU_RangeProcDSP_Config *rangeCfg)
static int32_t DPC_ObjDetDSP_rangeConfig (DPU_RangeProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, int16_t *window, uint32_t windowSize, cmplx16ImRe_t *twiddle, uint32_t twiddleSize, DPU_RangeProcDSP_Config *cfgSave)
static void DPC_ObjDetDSP_quadFit (float *x, float *y, float *xv, float *yv)
static void DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure (DPC_ObjectDetection_StaticCfg *staticCfg, float targetDistance, float searchWinSize, uint16_t *detMatrix, uint32_t *symbolMatrix, DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static uint32_t DPC_ObjDetDSP_GetDopplerWinGenLen (uint16_t numDopplerChirps)
static uint32_t DPC_ObjDetDSP_GenDopplerWindow (DPU_DopplerProcDSP_Config *cfg)
static void DPC_ObjDetDSP_GetRxChPhaseComp (DPC_ObjectDetection_StaticCfg *staticCfg, DPU_AoAProc_compRxChannelBiasCfg *inpCfg, DPU_AoAProc_compRxChannelBiasCfg *outCfg)
static int32_t DPC_ObjDetDSP_reconfigSubFrame (ObjDetObj *objDetObj, uint8_t subFrameIndx)
static int32_t DPC_ObjDetDSP_initDPU (ObjDetObj *objDetObj, uint8_t numSubFrames)
static int32_t DPC_ObjDetDSP_deinitDPU (ObjDetObj *objDetObj, uint8_t numSubFrames)
static int32_t DPC_ObjDetDSP_Config_MeasureRxChannelBiasCfg (ObjDetObj *obj, DPC_ObjectDetection_MeasureRxChannelBiasCfg *cfg)
static int32_t DPC_ObjDetDSP_dopplerConfig (DPU_DopplerProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_DetMatrix *detMatrix, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, int32_t *window, uint32_t windowSize, cmplx32ReIm_t *twiddleBuf, uint32_t twiddleSize, cmplx16ImRe_t *dftSinCosTable, uint32_t dftSinCosTableSize, DPU_DopplerProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_CFARCAconfig (DPU_CFARCAProcDSP_Handle dpuHandle, SubFrameObj *subFrameObj, EDMA_Handle edmaHandle, DPIF_DetMatrix *detMatrix, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, float rangeBias, DPU_CFARCAProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_AoAconfig (DPU_AoAProcDSP_Handle dpuHandle, DPU_AoAProc_compRxChannelBiasCfg *inpCommonCompRxCfg, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreL1RamObj, MemPoolObj *CoreL2RamObj, MemPoolObj *L3RamObj, int32_t *window, uint32_t windowSize, cmplx32ReIm_t *twiddleBuf, uint32_t twiddleSize, cmplx32ReIm_t *angleTwiddle32x32, uint32_t angleTwiddle32x32Size, DPU_AoAProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_preStartConfig (SubFrameObj *subFrameObj, DPC_ObjectDetection_PreStartCommonCfg *commonCfg, DPC_ObjectDetection_PreStartCfg *preStartCfg, EDMA_Handle edmaHandle[EDMA_NUM_CC], MemPoolObj *L3ramObj, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, uint32_t *L3RamUsage, uint32_t *CoreL2RamUsage, uint32_t *CoreL1RamUsage)
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer *ptrResult)
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void *arg, uint32_t argLen)
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg *ptrInitCfg, int32_t *errCode)
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle)
Detailed Description
This section has a list of all the internal function which are a part of the DPC. These are not exposed to the application.
Function Documentation
DPC_ObjDetDSP_AoAconfig()
static int32_t DPC_ObjDetDSP_AoAconfig (DPU_AoAProcDSP_Handle dpuHandle, DPU_AoAProc_compRxChannelBiasCfg * inpCommonCompRxCfg, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, DPIF_CFARDetList * cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj * CoreL1RamObj, MemPoolObj * CoreL2RamObj, MemPoolObj * L3RamObj, int32_t * window, uint32_t windowSize, cmplx32ReIm_t * twiddleBuf, uint32_t twiddleSize, cmplx32ReIm_t * angleTwiddle32x32, uint32_t angleTwiddle32x32Size, DPU_AoAProcDSP_Config * cfgSave) static
Description
Configure AoA DPU. Note window information is passed to this function that is expected to be the same that was used in doppler processing because the AoA recomputes the doppler (2D) FFT. The reason for this recompute is because doppler does not update the radar cube (radar cube is range (1D) output). The window is used in AoA only for doppler FFT recompute, no window (in other words rectangular) is used for angle (3D) FFT computation. Note no DPIF info is passed here for AoA output because these DPIF buffers are not required to be shared with any other DPUs (but only at the exit f DPC's processing chain which will be consumed by the app) hence they are allocated within this function, this way more allocation remains localized in this function instead of being managed by the caller.
Parameters
[in] dpuHandle Handle to DPU
[in] inpCommonCompRxCfg Range bias and rx phase compensation common (across sub-frames) configuration, this will be used to extract the rx phase for sub-frame specific configuration based on antenna order.
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which will be the input for AoA processing
[in] cfarRngDopSnrList Pointer to range-doppler SNR list, which will be input for AoA processing
[in] cfarRngDopSnrListSize Range-doppler SNR List Size to which the list was capped by cfar processing
[in] CoreL1RamObj Pointer to core local L1 RAM object to allocate local memory for the DPU, all allocated memory will be permanent (within frame/sub-frame)
[in] CoreL2RamObj Pointer to core local L2 RAM object to allocate local memory for the DPU, all allocated memory will be permanent (within frame/sub-frame)
[in] L3RamObj Pointer to L3 RAM object to allocate L3RAM memory for the DPU, all allocated memory will be permanent (within frame/sub-frame)
[in] window Pointer to AoA doppler FFT window coefficients buffer
[in] windowSize AoA Doppler FFT window size in bytes. See AoA DPU configuration for more information.
[in] twiddleBuf Pointer to AoA doppler FFT twiddle buffer
[in] twiddleSize Doppler FFT twiddle buffer size in bytes. See AoA DPU configuration for more information.
[in] angleTwiddle32x32 Pointer to angle 3D FFT twiddle buffer
[in] angleTwiddle32x32Size 3D (Azimuth/Elevation) FFT twiddle buffer size in bytes. See AoA DPU configuration for more information.
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1507 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPU_AoAProcDSP_Resources_t::angleFftIn, DPU_AoAProcDSP_Resources_t::angleFftInSize, DPU_AoAProcDSP_Resources_t::angleTwiddle32x32, DPU_AoAProcDSP_Resources_t::angleTwiddleSize, DPU_AoAProcDSP_Resources_t::azimuthStaticHeatMap, DPU_AoAProcDSP_Resources_t::azimuthStaticHeatMapSize, DPC_ObjectDetection_StaticCfg_t::centerFreq, DPU_AoAProcDSP_Resources_t::cfarRngDopSnrList, DPU_AoAProcDSP_Resources_t::cfarRngDopSnrListSize, DPU_AoAProc_DynamicConfig_t::compRxChanCfg, DPIF_ADCBufData_t::dataProperty, DPU_AoAProcDSP_Resources_t::detObj2dAzimIdx, DPU_AoAProcDSP_Resources_t::detObjElevationAngle, DPU_AoAProcDSP_Resources_t::detObjOut, DPU_AoAProcDSP_Resources_t::detObjOutMaxSize, DPU_AoAProcDSP_Resources_t::detObjOutSideInfo, DPU_AoAProcDSP_StaticConfig_t::dopplerStep, DPC_ObjectDetection_StaticCfg_t::dopplerStep, DPC_OBJDET_AZIMUTH_STATIC_HEAT_MAP_BYTE_ALIGNMENT, DPC_OBJDET_DET_OBJ_ELEVATION_ANGLE_BYTE_ALIGNMENT, DPC_OBJDET_MAX_NUM_OBJECTS, DPC_OBJDET_POINT_CLOUD_CARTESIAN_BYTE_ALIGNMENT, DPC_OBJDET_POINT_CLOUD_SIDE_INFO_BYTE_ALIGNMENT, DPC_ObjDetDSP_GetRxChPhaseComp(), DPC_ObjDetDSP_MemPoolAlloc(), DPU_AOAPROCDSP_BUFFERS_BYTE_ALIGNMENT, DPU_AoAProcDSP_config(), DPU_AOAPROCDSP_NUM_ANGLE_BINS, DPU_AoAProcDSP_Config_t::dynCfg, DPU_AoAProcDSP_Resources_t::edmaHandle, DPU_AoAProcDSP_Resources_t::edmaPing, DPU_AoAProcDSP_Resources_t::edmaPong, DPU_AoAProcDSP_Resources_t::elevationFftOut, DPU_AoAProcDSP_Resources_t::elevationFftOutSize, DPC_ObjectDetection_StaticClutterRemovalCfg_Base_t::enabled, DPU_AoAProc_DynamicConfig_t::extMaxVelCfg, DPC_ObjectDetection_DynCfg_t::extMaxVelCfg, DPU_AoAProc_DynamicConfig_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPU_AoAProcDSP_StaticConfig_t::isBpmEnabled, DPC_ObjectDetection_StaticCfg_t::isBpmEnabled, DPU_AoAProc_StaticClutterRemovalCfg_t::isEnabled, DPU_AoAProcDSP_StaticConfig_t::lambdaOverDist, DPU_AoAProc_DynamicConfig_t::multiObjBeamFormingCfg, DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, DPU_AoAProcDSP_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_AoAProcDSP_StaticConfig_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPU_AoAProcDSP_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_AoAProcDSP_StaticConfig_t::numRxAntennas, DPIF_ADCBufProperty_t::numRxAntennas, DPU_AoAProcDSP_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_AoAProcDSP_StaticConfig_t::numVirtualAntAzim, DPC_ObjectDetection_StaticCfg_t::numVirtualAntAzim, DPU_AoAProcDSP_StaticConfig_t::numVirtualAntElev, DPC_ObjectDetection_StaticCfg_t::numVirtualAntElev, DPU_AoAProcDSP_Resources_t::pingPongBuf, DPU_AoAProcDSP_Resources_t::pingPongSize, DPU_AoAProc_DynamicConfig_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, DPU_AoAProcDSP_Resources_t::radarCube, DPU_AoAProcDSP_StaticConfig_t::rangeStep, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_AoAProcDSP_Config_t::res, DPU_AoAProcDSP_Resources_t::scratch1Buff, DPU_AoAProcDSP_Resources_t::scratch1Size, DPU_AoAProcDSP_Resources_t::scratch2Buff, DPU_AoAProcDSP_Resources_t::scratch2Size, DPU_AoAProcDSP_Config_t::staticCfg, DPU_AoAProc_DynamicConfig_t::staticClutterCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, DPU_AoAProcDSP_Resources_t::twiddle32x32, DPU_AoAProcDSP_Resources_t::twiddleSize, DPU_AoAProcDSP_Resources_t::windowCoeff, and DPU_AoAProcDSP_Resources_t::windowSize.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_CFARCAconfig()
static int32_t DPC_ObjDetDSP_CFARCAconfig (DPU_CFARCAProcDSP_Handle dpuHandle, SubFrameObj * subFrameObj, EDMA_Handle edmaHandle, DPIF_DetMatrix * detMatrix, DPIF_CFARDetList * cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj * CoreL2RamObj, MemPoolObj * CoreL1RamObj, float rangeBias, DPU_CFARCAProcDSP_Config * cfgSave) static
Description
Configure CFARCA DPU.
Parameters
[in] dpuHandle Handle to CFARCA DPU
[in] subFrameObj Pointer to subFrame data object
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] detMatrix Pointer to DPIF detection matrix, which will be the input to the CFARCA
[in] cfarRngDopSnrList Pointer to range-doppler SNR list, which will be the output of CFARCA
[in] cfarRngDopSnrListSize Range-doppler SNR List Size to which the list will be capped.
[in] CoreL2RamObj Pointer to core local L2 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] CoreL1RamObj Pointer to core local L1 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] rangeBias Range Bias which will be used to adjust fov min value.
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1346 of file objectdetection.c.
References DPU_CFARCAProcDSP_DynamicConfig_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPU_CFARCAProcDSP_DynamicConfig_t::cfarCfgRange, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, DPU_CFARCAProcDSP_HW_Resources_t::cfarDetOutBuffer, DPU_CFARCAProcDSP_HW_Resources_t::cfarDetOutBufferSize, DPU_CFARCAProcDSP_HW_Resources_t::cfarDopplerDetOutBitMask, DPU_CFARCAProcDSP_HW_Resources_t::cfarDopplerDetOutBitMaskSize, DPU_CFARCAProcDSP_HW_Resources_t::cfarRngDopSnrList, DPU_CFARCAProcDSP_HW_Resources_t::cfarRngDopSnrListSize, DPU_CFARCAProcDSP_HW_Resources_t::cfarScrachBuffer, DPU_CFARCAProcDSP_HW_Resources_t::cfarScrachBufferSize, DPU_CFARCAProcDSP_HW_Resources_t::detMatrix, DPU_CFARCAProcDSP_StaticConfig_t::dopplerStep, DPC_ObjectDetection_StaticCfg_t::dopplerStep, DPC_OBJDET_MAX_NUM_OBJECTS, DPC_ObjDetDSP_MemPoolAlloc(), DPU_CFAR_PEAK_GROUPING_DET_MATRIX_BASED, DPU_CFARCAPROCDSP_CFAR_DETOUT_BYTE_ALIGNMENT, DPU_CFARCAProcDSP_config(), DPU_CFARCAPROCDSP_DET_MATRIX_LOCAL_BYTE_ALIGNMENT, DPU_CFARCAPROCDSP_DOPPLER_DET_OUT_BIT_MASK_BYTE_ALIGNMENT, DPU_CFARCAPROCDSP_SCRACHBUF_BYTE_ALIGNMENT, DPU_CFARCAProcDSP_Config_t::dynCfg, SubFrameObj_t::dynCfg, DPU_CFARCAProcDSP_HW_Resources_t::edmaHandle, DPU_CFARCAProcDSP_HW_Resources_t::edmaInPing, DPU_CFARCAProcDSP_HW_Resources_t::edmaInPong, DPU_CFARCAProcDSP_DynamicConfig_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPU_CFARCAProcDSP_DynamicConfig_t::fovRange, DPC_ObjectDetection_DynCfg_t::fovRange, DPU_CFARCAProcDSP_HW_Resources_t::localDetMatrixBuffer, DPU_CFARCAProcDSP_HW_Resources_t::localDetMatrixBufferSize, DPU_CFARCAProcDSP_StaticConfig_t::log2NumDopplerBins, SubFrameObj_t::log2NumDopplerBins, DPU_CFARCAProc_FovCfg_t::min, DPU_CFARCAProcDSP_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_CFARCAProcDSP_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_CFARCAProc_CfarCfg_t::peakGroupingScheme, DPU_CFARCAProcDSP_StaticConfig_t::rangeStep, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_CFARCAProcDSP_Config_t::res, DPU_CFARCAProcDSP_Config_t::staticCfg, and SubFrameObj_t::staticCfg.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_Config_MeasureRxChannelBiasCfg()
static int32_t DPC_ObjDetDSP_Config_MeasureRxChannelBiasCfg (ObjDetObj * obj, DPC_ObjectDetection_MeasureRxChannelBiasCfg * cfg) static
Description
Configures DPC for Range Bias and Phase Comp measurement.
Parameters
[in] obj Pointer to DPC object
[in] cfg Pointer to Range Bias and Phase Comp measurement configuration
Return values
Success - 0
Error - <0
Definition at line 1128 of file objectdetection.c.
References ObjDetObj_t::commonCfg, DPC_OBJECTDETECTION_EINVAL__MEASURE_RX_CHANNEL_BIAS_CFG, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::searchWinSize, and DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::targetDistance.
Referenced by DPC_ObjectDetection_ioctl().
DPC_ObjDetDSP_deinitDPU()
static int32_t DPC_ObjDetDSP_deinitDPU (ObjDetObj * objDetObj, uint8_t numSubFrames) inline static
Description
Function to de-initialize all DPUs used in the DPC chain
Parameters
[in] objDetObj Pointer to sub-frame object
[in] numSubFrames Number of sub-frames
Return values
Success - 0
Error - <0
Definition at line 1068 of file objectdetection.c.
References DPU_AoAProcDSP_deinit(), DPU_CFARCAProcDSP_deinit(), DPU_DopplerProcDSP_deinit(), DPU_RangeProcDSP_deinit(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_deinit().
DPC_ObjDetDSP_dopplerConfig()
static int32_t DPC_ObjDetDSP_dopplerConfig (DPU_DopplerProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, DPIF_DetMatrix * detMatrix, MemPoolObj * CoreL2RamObj, MemPoolObj * CoreL1RamObj, int32_t * window, uint32_t windowSize, cmplx32ReIm_t * twiddleBuf, uint32_t twiddleSize, cmplx16ImRe_t * dftSinCosTable, uint32_t dftSinCosTableSize, DPU_DopplerProcDSP_Config * cfgSave) static
Description
Configure Doppler DPU.
Parameters
[in] dpuHandle Handle to Doppler DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] log2NumDopplerBins log2 of numDopplerBins of the static config.
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which will be the input to doppler processing
[in] detMatrix Pointer to DPIF detection matrix, which will be the output of doppler processing
[in] CoreL2RamObj Pointer to core local L2 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] CoreL1RamObj Pointer to core local L1 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] window Pointer to doppler FFT window coefficients buffer
[in] windowSize Doppler FFT window size in bytes. See Doppler DPU configuration for more information.
[in] twiddleBuf Pointer to doppler FFT twiddle buffer
[in] twiddleSize Doppler FFT twiddle buffer size in bytes. See Doppler DPU configuration for more information.
[in] dftSinCosTable Pointer to DFT Sin/Cos table buffer
[in] dftSinCosTableSize DFT Sin/Cos Table size in bytes. See Doppler DPU configuration for more information.
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 1186 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPU_DopplerProcDSP_HW_Resources_t::detMatrix, DPU_DopplerProcDSP_HW_Resources_t::dftSinCosSize, DPU_DopplerProcDSP_HW_Resources_t::dftSinCosTable, DPC_ObjDetDSP_GenDopplerWindow(), DPC_ObjDetDSP_MemPoolAlloc(), DPU_DOPPLERPROCDSP_BUFFER_BYTE_ALIGNMENT, DPU_DopplerProcDSP_config(), DPU_DopplerProcDSP_Config_t::dynCfg, DPU_DopplerProcDSP_HW_Resources_t::edmaCfg, DPU_DopplerProcDSP_EdmaCfg_t::edmaHandle, DPU_DopplerProcDSP_EdmaCfg_t::edmaIn, DPU_DopplerProcDSP_EdmaCfg_t::edmaOut, DPC_ObjectDetection_StaticClutterRemovalCfg_Base_t::enabled, DPU_DopplerProcDSP_HW_Resources_t::fftOutBuf, DPU_DopplerProcDSP_HW_Resources_t::fftOutSize, DPU_DopplerProcDSP_Config_t::hwRes, DPU_DopplerProcDSP_StaticConfig_t::isBpmEnabled, DPC_ObjectDetection_StaticCfg_t::isBpmEnabled, DPU_DopplerProc_StaticClutterRemovalCfg_t::isEnabled, DPU_DopplerProcDSP_StaticConfig_t::log2NumDopplerBins, DPU_DopplerProcDSP_StaticConfig_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPU_DopplerProcDSP_StaticConfig_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPU_DopplerProcDSP_StaticConfig_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_DopplerProcDSP_StaticConfig_t::numRxAntennas, DPIF_ADCBufProperty_t::numRxAntennas, DPU_DopplerProcDSP_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_DopplerProcDSP_StaticConfig_t::numVirtualAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_DopplerProc_Edma_t::ping, DPU_DopplerProcDSP_HW_Resources_t::pingPongBuf, DPU_DopplerProcDSP_HW_Resources_t::pingPongSize, DPU_DopplerProc_Edma_t::pong, DPU_DopplerProcDSP_HW_Resources_t::radarCube, DPU_DopplerProcDSP_Config_t::staticCfg, DPU_DopplerProcDSP_DynamicConfig_t::staticClutterCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, DPU_DopplerProcDSP_HW_Resources_t::sumAbsBuf, DPU_DopplerProcDSP_HW_Resources_t::sumAbsSize, DPU_DopplerProcDSP_HW_Resources_t::twiddle32x32, DPU_DopplerProcDSP_HW_Resources_t::twiddleSize, DPU_DopplerProcDSP_HW_Resources_t::windowCoeff, DPU_DopplerProcDSP_HW_Resources_t::windowingLog2AbsBuf, DPU_DopplerProcDSP_HW_Resources_t::windowingLog2AbsSize, and DPU_DopplerProcDSP_HW_Resources_t::windowSize.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_GenDopplerWindow()
static uint32_t DPC_ObjDetDSP_GenDopplerWindow (DPU_DopplerProcDSP_Config * cfg) static
Description
Generate the doppler DPU window using mmwavelib API.
Parameters
[in] cfg Doppler DPU configuration, output window is generated in window pointer embedded in this configuration.
Return values
winType window type, see mathutils.h
Definition at line 852 of file objectdetection.c.
References DPC_DPU_DOPPLERPROC_FFT_WINDOW_TYPE, DPC_OBJDET_QFORMAT_DOPPLER_FFT, DPC_ObjDetDSP_genWindow(), DPC_ObjDetDSP_GetDopplerWinGenLen(), DPU_DopplerProcDSP_Config_t::hwRes, DPU_DopplerProcDSP_StaticConfig_t::numDopplerChirps, DPU_DopplerProcDSP_Config_t::staticCfg, and DPU_DopplerProcDSP_HW_Resources_t::windowCoeff.
Referenced by DPC_ObjDetDSP_dopplerConfig(), and DPC_ObjDetDSP_reconfigSubFrame().
DPC_ObjDetDSP_GenRangeWindow()
static void DPC_ObjDetDSP_GenRangeWindow (DPU_RangeProcDSP_Config * rangeCfg) static
Description
Generate the range DPU window using mathutils API.
Parameters
[in] rangeCfg Range DPU configuration, output window is generated in window pointer in the staticCfg of this.
Return values
None
Definition at line 470 of file objectdetection.c.
References DPU_RangeProcDSP_StaticConfig_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE, DPC_OBJDET_QFORMAT_RANGE_FFT, DPC_ObjDetDSP_genWindow(), DPC_ObjDetDSP_GetRangeWinGenLen(), DPU_RangeProcDSP_Config_t::hwRes, DPIF_ADCBufProperty_t::numAdcSamples, DPU_RangeProcDSP_Config_t::staticCfg, and DPU_RangeProcDSP_HW_Resources_t::window.
Referenced by DPC_ObjDetDSP_rangeConfig(), and DPC_ObjDetDSP_reconfigSubFrame().
DPC_ObjDetDSP_GetDopplerWinGenLen()
static uint32_t DPC_ObjDetDSP_GetDopplerWinGenLen (uint16_t numDopplerChirps) static
Description
Computes the length of window to generate for doppler DPU.
Parameters
[in] numDopplerChirps Number of Doppler chirps
Return values
Length of window to generate
Definition at line 835 of file objectdetection.c.
Referenced by DPC_ObjDetDSP_GenDopplerWindow(), and DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_GetRangeWinGenLen()
static uint32_t DPC_ObjDetDSP_GetRangeWinGenLen (uint16_t numAdcSamples) static
Description
Computes the length of window to generate for range DPU.
Parameters
[in] numAdcSamples Number of ADC samples
Return values
Length of window to generate
Definition at line 453 of file objectdetection.c.
Referenced by DPC_ObjDetDSP_GenRangeWindow(), and DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_GetRxChPhaseComp()
static void DPC_ObjDetDSP_GetRxChPhaseComp (DPC_ObjectDetection_StaticCfg * staticCfg, DPU_AoAProc_compRxChannelBiasCfg * inpCfg, DPU_AoAProc_compRxChannelBiasCfg * outCfg) static
Description
Extracts the sub-frame specific vector from the common (full vector for all antennnas) input vector of the range bias and rx phase compensation. Uses the antenna order of the sub-frame.
Parameters
[in] staticCfg Static configuration of the sub-frame
[in] inpCfg The full vector.
[out] outCfg Sub-frame specific compensation vector that will be used during processing
Return values
None
Definition at line 893 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_ObjectDetection_StaticCfg_t::isValidProfileHasOneTxPerChirp, DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DPC_ObjectDetection_StaticCfg_t::rxAntOrder, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, and DPC_ObjectDetection_StaticCfg_t::txAntOrder.
Referenced by DPC_ObjDetDSP_AoAconfig(), DPC_ObjDetDSP_reconfigSubFrame(), and DPC_ObjectDetection_ioctl().
DPC_ObjDetDSP_initDPU()
static int32_t DPC_ObjDetDSP_initDPU (ObjDetObj * objDetObj, uint8_t numSubFrames) inline static
Description
Function to initialize all DPUs used in the DPC chain
Parameters
[in] objDetObj Pointer to sub-frame object
[in] numSubFrames Number of sub-frames
Return values
Success - 0
Error - <0
Definition at line 1008 of file objectdetection.c.
References DPU_AoAProcDSP_init(), DPU_CFARCAProcDSP_init(), DPU_DopplerProcDSP_init(), DPU_RangeProcDSP_init(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_init().
DPC_ObjDetDSP_MemPoolAlloc()
static void* DPC_ObjDetDSP_MemPoolAlloc (MemPoolObj * pool, uint32_t size, uint8_t align) static
Description
Utility function for allocating from a static memory pool.
Parameters
[in] pool Handle to pool object.
[in] size Size in bytes to be allocated.
[in] align Alignment in bytes
Return values
pointer to beginning of allocated block. NULL indicates could not allocate.
Definition at line 311 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, MemPoolObj_t::maxCurrAddr, and DPC_ObjectDetection_MemCfg_t::size.
Referenced by DPC_ObjDetDSP_AoAconfig(), DPC_ObjDetDSP_CFARCAconfig(), DPC_ObjDetDSP_dopplerConfig(), DPC_ObjDetDSP_preStartConfig(), and DPC_ObjDetDSP_rangeConfig().
DPC_ObjDetDSP_MemPoolGet()
static void* DPC_ObjDetDSP_MemPoolGet (MemPoolObj * pool) static
Description
Utility function for getting memory pool current address.
Parameters
[in] pool Handle to pool object.
Return values
pointer to current address of the pool (from which next allocation will allocate to the desired alignment).
Definition at line 274 of file objectdetection.c.
References MemPoolObj_t::currAddr.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_MemPoolGetMaxUsage()
static uint32_t DPC_ObjDetDSP_MemPoolGetMaxUsage (MemPoolObj * pool) static
Description
Utility function for getting maximum memory pool usage.
Parameters
[in] pool Handle to pool object.
Return values
Amount of pool used in bytes.
Definition at line 291 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_MemPoolReset()
static void DPC_ObjDetDSP_MemPoolReset (MemPoolObj * pool) static
Description
Utility function for reseting memory pool.
Parameters
[in] pool Handle to pool object.
Return values
none.
Definition at line 235 of file objectdetection.c.
References DPC_ObjectDetection_MemCfg_t::addr, MemPoolObj_t::cfg, MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_MemPoolSet()
static void DPC_ObjDetDSP_MemPoolSet (MemPoolObj * pool, void * addr) static
Description
Utility function for setting memory pool to desired address in the pool. Helps to rewind for example.
Parameters
[in] pool Handle to pool object.
[in] addr Address to assign to the pool's current address.
Return values
None
Definition at line 255 of file objectdetection.c.
References MemPoolObj_t::currAddr, and MemPoolObj_t::maxCurrAddr.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_preStartConfig()
static int32_t DPC_ObjDetDSP_preStartConfig (SubFrameObj * subFrameObj, DPC_ObjectDetection_PreStartCommonCfg * commonCfg, DPC_ObjectDetection_PreStartCfg * preStartCfg, EDMA_Handle edmaHandle[EDMA_NUM_CC], MemPoolObj * L3ramObj, MemPoolObj * CoreL2RamObj, MemPoolObj * CoreL1RamObj, uint32_t * L3RamUsage, uint32_t * CoreL2RamUsage, uint32_t * CoreL1RamUsage) static
Description
Performs processing related to pre-start configuration, which is per sub-frame, by configuring each of the DPUs involved in the processing chain. Memory management notes:
Core Local Memory that needs to be preserved across sub-frames (such as range DPU's calib DC buffer) will be allocated using MemoryP_alloc.
Core Local Memory that needs to be preserved within a sub-frame across DPU calls (the DPIF * type memory) or for intermediate private scratch memory for DPU (i.e no preservation is required from process call to process call of the DPUs within the sub-frame) will be allocated from the Core Local RAM configuration supplied in DPC_ObjectDetection_InitParams given to DPC_ObjectDetection_init API
L3 memory will only be allocated from the L3 RAM configuration supplied in DPC_ObjectDetection_InitParams given to DPC_ObjectDetection_init API No L3 buffers are presently required that need to be preserved across sub-frames (type described in #1 above), neither are L3 scratch buffers required for intermediate processing within DPU process call.
Parameters
[in] subFrameObj Pointer to sub-frame object
[in] commonCfg Pointer to pre-start common configuration
[in] preStartCfg Pointer to pre-start configuration of the sub-frame
[in] edmaHandle Pointer to array of EDMA handles for the device, this can be distributed among the DPUs, the actual EDMA handle used in DPC is determined by definition in application resource file
[in] L3ramObj Pointer to L3 RAM memory pool object
[in] CoreL2RamObj Pointer to Core Local L2 memory pool object
[in] CoreL1RamObj Pointer to Core Local L1 memory pool object
[out] L3RamUsage Net L3 RAM memory usage in bytes as a result of allocation by the DPUs.
[out] CoreL2RamUsage Net Local L2 RAM memory usage in bytes
[out] CoreL1RamUsage Net Core L1 RAM memory usage in bytes
Return values
Success - 0
Error - <0
Definition at line 1713 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPC_ObjectDetection_MemCfg_t::addr, DpuConfigs_t::aoaCfg, DpuConfigs_t::cfarCfg, MemPoolObj_t::cfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DPIF_RadarCube_t::data, DPIF_DetMatrix_t::data, DPIF_RadarCube_t::datafmt, DPIF_DetMatrix_t::datafmt, DPIF_ADCBufData_t::dataProperty, DPIF_RadarCube_t::dataSize, DPIF_DetMatrix_t::dataSize, DpuConfigs_t::dopplerCfg, DPC_OBJDET_CFAR_DET_LIST_BYTE_ALIGNMENT, DPC_OBJDET_DET_MATRIX_DATABUF_BYTE_ALIGNMENT, DPC_OBJDET_MAX_NUM_OBJECTS, DPC_OBJDET_RADAR_CUBE_DATABUF_BYTE_ALIGNMENT, DPC_ObjDetDSP_AoAconfig(), DPC_ObjDetDSP_CFARCAconfig(), DPC_ObjDetDSP_dopplerConfig(), DPC_ObjDetDSP_GetDopplerWinGenLen(), DPC_ObjDetDSP_GetRangeWinGenLen(), DPC_ObjDetDSP_MemPoolAlloc(), DPC_ObjDetDSP_MemPoolGet(), DPC_ObjDetDSP_MemPoolGetMaxUsage(), DPC_ObjDetDSP_MemPoolReset(), DPC_ObjDetDSP_MemPoolSet(), DPC_ObjDetDSP_rangeConfig(), DPC_OBJECTDETECTION_EINVAL__COMMAND, DPC_OBJECTDETECTION_ENOMEM__L3_RAM_DET_MATRIX, DPC_OBJECTDETECTION_ENOMEM__L3_RAM_RADAR_CUBE, DPIF_DETMATRIX_FORMAT_1, DPIF_RADARCUBE_FORMAT_1, DPU_AOAPROCDSP_BUFFERS_BYTE_ALIGNMENT, DPU_AOAPROCDSP_NUM_ANGLE_BINS, DPU_DOPPLERPROCDSP_BUFFER_BYTE_ALIGNMENT, DPU_RANGEPROCDSP_TWIDDLEBUF_BYTE_ALIGNMENT_DSP, DPU_RANGEPROCDSP_WINDOW_BYTE_ALIGNMENT_DSP, SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, SubFrameObj_t::dynCfg, DPC_ObjectDetection_PreStartCfg_t::dynCfg, DPC_ObjectDetection_ShareMemCfg_t::L3Ram, SubFrameObj_t::log2NumDopplerBins, DPIF_ADCBufProperty_t::numAdcSamples, DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPC_ObjectDetection_ShareMemCfg_t::radarCubeMem, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DpuConfigs_t::rangeCfg, DPC_ObjectDetection_PreStartCfg_t::shareMemCfg, DPC_ObjectDetection_ShareMemCfg_t::shareMemEnable, DPC_ObjectDetection_MemCfg_t::size, SubFrameObj_t::staticCfg, and DPC_ObjectDetection_PreStartCfg_t::staticCfg.
Referenced by DPC_ObjectDetection_ioctl().
DPC_ObjDetDSP_quadFit()
static void DPC_ObjDetDSP_quadFit (float * x, float * y, float * xv, float * yv) static
Description
Utility function to do a parabolic/quadratic fit on 3 input points and return the coordinates of the peak. This is used to accurately estimate range bias.
Parameters
[in] x Pointer to array of 3 elements representing the x-coordinate of the points to fit
[in] y Pointer to array of 3 elements representing the y-coordinate of the points to fit
[out] xv Pointer to output x-coordinate of the peak value
[out] yv Pointer to output y-coordinate of the peak value
Return values
None
Definition at line 667 of file objectdetection.c.
Referenced by DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure().
DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure()
static void DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure (DPC_ObjectDetection_StaticCfg * staticCfg, float targetDistance, float searchWinSize, uint16_t * detMatrix, uint32_t * symbolMatrix, DPU_AoAProc_compRxChannelBiasCfg * compRxChanCfg) static
Description
Computes the range bias and rx phase compensation from the detection matrix during calibration measurement procedure of these parameters.
Parameters
[in] staticCfg Pointer to static configuration
[in] targetDistance Target distance in meters
[in] searchWinSize Search window size in meters
[in] detMatrix Pointer to detection matrix
[in] symbolMatrix Pointer to symbol matrix
[out] compRxChanCfg computed output range bias and rx phase comp vector
Return values
None
Definition at line 703 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPIF_ADCBufData_t::dataProperty, DPC_ObjDetDSP_quadFit(), DPC_ObjectDetection_StaticCfg_t::numDopplerBins, DPC_ObjectDetection_StaticCfg_t::numDopplerChirps, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DPC_ObjectDetection_StaticCfg_t::rangeStep, DPU_AoAProc_compRxChannelBiasCfg_t::rxChPhaseComp, and DPC_ObjectDetection_StaticCfg_t::txAntOrder.
Referenced by DPC_ObjectDetection_execute().
DPC_ObjDetDSP_rangeConfig()
static int32_t DPC_ObjDetDSP_rangeConfig (DPU_RangeProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg * staticCfg, DPC_ObjectDetection_DynCfg * dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube * radarCube, MemPoolObj * CoreL2RamObj, MemPoolObj * CoreL1RamObj, int16_t * window, uint32_t windowSize, cmplx16ImRe_t * twiddle, uint32_t twiddleSize, DPU_RangeProcDSP_Config * cfgSave) static
Description
Configure range DPU.
Parameters
[in] dpuHandle Handle to Range DPU
[in] staticCfg Pointer to static configuration of the sub-frame
[in] dynCfg Pointer to dynamic configuration of the sub-frame
[in] edmaHandle Handle to edma driver to be used for the DPU
[in] radarCube Pointer to DPIF radar cube, which is output of range processing.
[in] CoreL2RamObj Pointer to core local L2 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] CoreL1RamObj Pointer to core local L1 RAM object to allocate local memory for the DPU, only for scratch purposes
[in] window Pointer to range FFT window coefficients buffer
[in] windowSize Range FFT window size in bytes. See Range DPU configuration for more information.
[in] twiddle Pointer to range FFT twiddle buffer
[in] twiddleSize Range FFT twiddle buffer size in bytes. See Range DPU configuration for more information.
[out] cfgSave Configuration that is built in local (stack) variable is saved here. This is for facilitating quick reconfiguration later without having to go through the construction of the configuration.
Return values
Success - 0
Error - <0
Definition at line 516 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DPU_RangeProcDSP_StaticConfig_t::ADCBufData, DPU_RangeProcDSP_HW_Resources_t::adcDataIn, DPU_RangeProcDSP_HW_Resources_t::adcDataInSize, DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPU_RangeProcDSP_DynamicConfig_t::calibDcRangeSigCfg, DPU_RangeProcDSP_EDMAConfig_t::dataInPing, DPU_RangeProcDSP_EDMAConfig_t::dataInPong, DPU_RangeProcDSP_EDMAConfig_t::dataOutPing, DPU_RangeProcDSP_EDMAConfig_t::dataOutPong, DPIF_ADCBufData_t::dataProperty, DPU_RangeProcDSP_HW_Resources_t::dcRangeSigMean, DPU_RangeProcDSP_HW_Resources_t::dcRangeSigMeanSize, DPC_ObjDetDSP_GenRangeWindow(), DPC_ObjDetDSP_MemPoolAlloc(), DPIF_RXCHAN_NON_INTERLEAVE_MODE, DPU_RANGEPROC_SIGNATURE_COMP_MAX_BIN_SIZE, DPU_RANGEPROCDSP_ADCDATAIN_BYTE_ALIGNMENT_DSP, DPU_RangeProcDSP_config(), DPU_RANGEPROCDSP_FFTOUT_BYTE_ALIGNMENT_DSP, DPU_RangeProcDSP_Config_t::dynCfg, DPU_RangeProcDSP_HW_Resources_t::edmaCfg, DPU_RangeProcDSP_EDMAConfig_t::edmaHandle, DPU_RangeProcDSP_HW_Resources_t::fftOut1D, DPU_RangeProcDSP_HW_Resources_t::fftOut1DSize, DPU_RangeProcDSP_Config_t::hwRes, DPIF_ADCBufProperty_t::interleave, DPC_ObjectDetection_StaticCfg_t::numChirpsPerFrame, DPU_RangeProcDSP_StaticConfig_t::numChirpsPerFrame, DPC_ObjectDetection_StaticCfg_t::numRangeBins, DPU_RangeProcDSP_StaticConfig_t::numRangeBins, DPIF_ADCBufProperty_t::numRxAntennas, DPC_ObjectDetection_StaticCfg_t::numTxAntennas, DPU_RangeProcDSP_StaticConfig_t::numTxAntennas, DPC_ObjectDetection_StaticCfg_t::numVirtualAntennas, DPU_RangeProcDSP_StaticConfig_t::numVirtualAntennas, DPU_RangeProcDSP_HW_Resources_t::radarCube, DPU_RangeProcDSP_StaticConfig_t::resetDcRangeSigMeanBuffer, DPU_RangeProcDSP_Config_t::staticCfg, DPU_RangeProcDSP_HW_Resources_t::twiddle16x16, DPU_RangeProcDSP_HW_Resources_t::twiddleSize, DPU_RangeProcDSP_HW_Resources_t::window, and DPU_RangeProcDSP_HW_Resources_t::windowSize.
Referenced by DPC_ObjDetDSP_preStartConfig().
DPC_ObjDetDSP_reconfigSubFrame()
static int32_t DPC_ObjDetDSP_reconfigSubFrame (ObjDetObj * objDetObj, uint8_t subFrameIndx) static
Description
Sub-frame reconfiguration, used when switching sub-frames. Invokes the DPU configuration using the configuration that was stored during the pre-start configuration so reconstruction time is saved because this will happen in real-time.
Parameters
[in] objDetObj Pointer to DPC object
[in] subFrameIndx Sub-frame index.
Return values
Success - 0
Error - <0
Definition at line 945 of file objectdetection.c.
References DpuConfigs_t::aoaCfg, DpuConfigs_t::cfarCfg, ObjDetObj_t::commonCfg, DPU_AoAProc_DynamicConfig_t::compRxChanCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, DpuConfigs_t::dopplerCfg, DPC_ObjDetDSP_GenDopplerWindow(), DPC_ObjDetDSP_GenRangeWindow(), DPC_ObjDetDSP_GetRxChPhaseComp(), DPU_AoAProcDSP_config(), DPU_CFARCAProcDSP_config(), DPU_DopplerProcDSP_config(), DPU_RangeProcDSP_config(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, DPU_AoAProcDSP_Config_t::dynCfg, DpuConfigs_t::rangeCfg, SubFrameObj_t::staticCfg, and ObjDetObj_t::subFrameObj.
Referenced by DPC_ObjectDetection_ioctl(), and DPC_ObjectDetection_start().
DPC_ObjectDetection_chirpEvent()
void DPC_ObjectDetection_chirpEvent (DPM_DPCHandle handle)
Description
DPC chirp event function registered with DPM. This is invoked on reception of the chirp data available ISR from the RF front-end. This API is also invoked when application issues DPC_OBJDET_IOCTL__TRIGGER_CHIRP to simulate a chirp event trigger (e.g for unit testing purpose).
Parameters
[in] handle DPM's DPC handle
Return values
Not applicable
Definition at line 416 of file objectdetection.c.
References ObjDetObj_t::chirpEndTime, ObjDetObj_t::chirpIndex, ObjDetObj_t::chirpMargin, DPM_notifyExecute(), and ObjDetObj_t::dpmHandle.
Referenced by DPC_ObjectDetection_ioctl().
DPC_ObjectDetection_deinit()
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) de-initialization function which is invoked by the application using DPM_deinit API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 2859 of file objectdetection.c.
References DPC_ObjDetDSP_deinitDPU(), and DPC_OBJECTDETECTION_EINVAL.
DPC_ObjectDetection_execute()
int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer * ptrResult) static
Description
DPC's (DPM registered) execute function which is invoked by the application in the DPM's execute context when the DPC issues DPM_notifyExecute API from its registered DPC_ObjectDetection_frameStart API that is invoked every frame interrupt.
Parameters
[in] handle DPM's DPC handle
[out] ptrResult Pointer to the result
Return values
Success - 0
Error - <0
Definition at line 2106 of file objectdetection.c.
References DPC_ObjectDetection_StaticCfg_t::ADCBufData, DpuConfigs_t::aoaCfg, DPU_AoAProcDSP_Resources_t::azimuthStaticHeatMap, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMap, DPU_AoAProcDSP_Resources_t::azimuthStaticHeatMapSize, DPC_ObjectDetection_ExecuteResult_t::azimuthStaticHeatMapSize, ObjDetObj_t::chirpEndTime, ObjDetObj_t::chirpIndex, ObjDetObj_t::chirpMargin, ObjDetObj_t::commonCfg, DPC_ObjectDetection_ExecuteResult_t::compRxChanBiasMeasurement, ObjDetObj_t::compRxChanCfgMeasureOut, DPIF_RadarCube_t::data, DPIF_DetMatrix_t::data, DPIF_ADCBufData_t::dataProperty, DPU_DopplerProcDSP_HW_Resources_t::detMatrix, DPC_ObjectDetection_ExecuteResult_t::detMatrix, DPU_AoAProcDSP_Resources_t::detObjOut, DPU_AoAProcDSP_Resources_t::detObjOutSideInfo, DpuConfigs_t::dopplerCfg, DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure(), DPM_MAX_BUFFER, DPU_AoAProcDSP_process(), DPU_CFARCAProcDSP_process(), DPU_DopplerProcDSP_process(), DPU_RangeProcDSP_process(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::enabled, DPU_RangeProcDSP_OutParams_t::endOfChirp, ObjDetObj_t::executeResult, DPU_DopplerProcDSP_Config_t::hwRes, DPC_ObjectDetection_Stats_t::interChirpProcessingMargin, DPC_ObjectDetection_Stats_t::interFrameEndTimeStamp, DPC_ObjectDetection_Stats_t::interFrameStartTimeStamp, DPC_ObjectDetection_PreStartCommonCfg_t::measureRxChannelBiasCfg, DPU_AoAProcDSP_OutParams_t::numAoADetectedPoints, DPU_CFARCAProcDSP_OutParams_t::numCfarDetectedPoints, DPIF_ADCBufProperty_t::numChirpsPerChirpEvent, DPC_ObjectDetection_StaticCfg_t::numChirpsPerFrame, DPC_ObjectDetection_ExecuteResult_t::numObjOut, DPC_ObjectDetection_ExecuteResult_t::objOut, DPC_ObjectDetection_ExecuteResult_t::objOutSideInfo, ObjDetObj_t::processCallBackCfg, DPC_ObjectDetection_ProcessCallBackCfg_t::processFrameBeginCallBackFxn, DPC_ObjectDetection_ProcessCallBackCfg_t::processInterFrameBeginCallBackFxn, DPM_Buffer_t::ptrBuffer, DPU_AoAProcDSP_Resources_t::radarCube, DPU_DopplerProcDSP_HW_Resources_t::radarCube, DPC_ObjectDetection_ExecuteResult_t::radarCube, DPU_AoAProcDSP_Config_t::res, DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::searchWinSize, DPM_Buffer_t::size, SubFrameObj_t::staticCfg, ObjDetObj_t::stats, DPC_ObjectDetection_ExecuteResult_t::stats, DPC_ObjectDetection_ExecuteResult_t::subFrameIdx, ObjDetObj_t::subFrameIndx, ObjDetObj_t::subFrameObj, and DPC_ObjectDetection_MeasureRxChannelBiasCfg_t::targetDistance.
DPC_ObjectDetection_frameStart()
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle) static
Description
DPC frame start function registered with DPM. This is invoked on reception of the frame start ISR from the RF front-end. This API is also invoked when application issues DPC_OBJDET_IOCTL__TRIGGER_FRAME to simulate a frame trigger (e.g for unit testing purpose).
Parameters
[in] handle DPM's DPC handle
Return values
Not applicable
Definition at line 1992 of file objectdetection.c.
References DPC_Objdet_Assert, ObjDetObj_t::dpmHandle, DPC_ObjectDetection_Stats_t::frameStartIntCounter, DPC_ObjectDetection_Stats_t::frameStartTimeStamp, ObjDetObj_t::interSubFrameProcToken, ObjDetObj_t::stats, and ObjDetObj_t::subFrameIndx.
Referenced by DPC_ObjectDetection_ioctl().
DPC_ObjectDetection_init()
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg * ptrInitCfg, int32_t * errCode) static
Description
DPC's (DPM registered) initialization function which is invoked by the application using DPM_init API. Among other things, this API allocates DPC instance and DPU instances (by calling DPU's init APIs) from the MemoryP osal heap. If this API returns an error of any type, the heap is not guaranteed to be in the same state as before calling the API (i.e any allocations from the heap while executing the API are not guaranteed to be deallocated in case of error), so any error from this API should be considered fatal and if the error is of _ENOMEM type, the application will have to be built again with a bigger heap size to address the problem.
Parameters
[in] dpmHandle DPM's DPC handle
[in] ptrInitCfg Handle to the framework semaphore
[out] errCode Error code populated on error
Return values
Success - 0
Error - <0
Definition at line 2771 of file objectdetection.c.
References DPM_InitCfg_t::arg, DPM_InitCfg_t::argSize, DPC_ObjectDetection_InitParams_t::CoreL1RamCfg, DPC_ObjectDetection_InitParams_t::CoreL2RamCfg, DPC_ObjDetDSP_initDPU(), DPC_OBJECTDETECTION_EINVAL, DPC_OBJECTDETECTION_EINVAL__INIT_CFG_ARGSIZE, DPC_OBJECTDETECTION_ENOMEM, DPC_ObjectDetection_InitParams_t::edmaHandle, gObjDetObj, DPC_ObjectDetection_InitParams_t::L3ramCfg, and DPC_ObjectDetection_InitParams_t::processCallBackCfg.
DPC_ObjectDetection_ioctl()
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void * arg, uint32_t argLen) static
Description
DPC IOCTL commands configuration API which will be invoked by the application using DPM_ioctl API
Parameters
[in] handle DPM's DPC handle
[in] cmd Capture DPC specific commands
[in] arg Command specific arguments
[in] argLen Length of the arguments which is also command specific
Return values
Success - 0
Error - <0
Definition at line 2264 of file objectdetection.c.
References DpuConfigs_t::aoaCfg, DPC_ObjectDetection_DynCfg_t::calibDcRangeSigCfg, DPC_ObjectDetection_DynCfg_t::cfarCfgDoppler, DPC_ObjectDetection_DynCfg_t::cfarCfgRange, MemPoolObj_t::cfg, DPC_ObjectDetection_CalibDcRangeSigCfg_t::cfg, DPC_ObjectDetection_CfarCfg_t::cfg, DPC_ObjectDetection_fovRangeCfg_t::cfg, DPC_ObjectDetection_fovDopplerCfg_t::cfg, DPC_ObjectDetection_MultiObjBeamFormingCfg_t::cfg, DPC_ObjectDetection_fovAoaCfg_t::cfg, DPC_ObjectDetection_extMaxVelCfg_t::cfg, DPC_ObjectDetection_StaticClutterRemovalCfg_t::cfg, ObjDetObj_t::commonCfg, DPC_ObjectDetection_PreStartCommonCfg_t::compRxChanCfg, ObjDetObj_t::CoreL1RamObj, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL1RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL1RamUsage, ObjDetObj_t::CoreL2RamObj, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL2RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::CoreL2RamUsage, DPU_RangeProcDSP_HW_Resources_t::dcRangeSigMean, DPU_RangeProcDSP_HW_Resources_t::dcRangeSigMeanSize, DpuConfigs_t::dopplerCfg, DPC_OBJDET_IOCTL__DYNAMIC_CALIB_DC_RANGE_SIG_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_DOPPLER_CFG, DPC_OBJDET_IOCTL__DYNAMIC_CFAR_RANGE_CFG, DPC_OBJDET_IOCTL__DYNAMIC_COMP_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_EXECUTE_RESULT_EXPORTED, DPC_OBJDET_IOCTL__DYNAMIC_EXT_MAX_VELOCITY, DPC_OBJDET_IOCTL__DYNAMIC_FOV_AOA, DPC_OBJDET_IOCTL__DYNAMIC_FOV_DOPPLER, DPC_OBJDET_IOCTL__DYNAMIC_FOV_RANGE, DPC_OBJDET_IOCTL__DYNAMIC_MEASURE_RANGE_BIAS_AND_RX_CHAN_PHASE, DPC_OBJDET_IOCTL__DYNAMIC_MULTI_OBJ_BEAM_FORM_CFG, DPC_OBJDET_IOCTL__DYNAMIC_RANGE_AZIMUTH_HEAT_MAP, DPC_OBJDET_IOCTL__DYNAMIC_STATICCLUTTER_REMOVAL_CFG, DPC_OBJDET_IOCTL__MAX, DPC_OBJDET_IOCTL__STATIC_PRE_START_CFG, DPC_OBJDET_IOCTL__STATIC_PRE_START_COMMON_CFG, DPC_OBJDET_IOCTL__TRIGGER_CHIRP, DPC_OBJDET_IOCTL__TRIGGER_FRAME, DPC_ObjDetDSP_Config_MeasureRxChannelBiasCfg(), DPC_ObjDetDSP_GetRxChPhaseComp(), DPC_ObjDetDSP_preStartConfig(), DPC_ObjDetDSP_reconfigSubFrame(), DPC_ObjectDetection_chirpEvent(), DPC_ObjectDetection_frameStart(), DPC_OBJECTDETECTION_PRE_START_CONFIG_BEFORE_PRE_START_COMMON_CONFIG, DPM_EINVCMD, DPU_AoAProcDSP_Cmd_CompRxChannelBiasCfg, DPU_AoAProcDSP_Cmd_ExtMaxVelocityCfg, DPU_AoAProcDSP_Cmd_FovAoACfg, DPU_AoAProcDSP_Cmd_MultiObjBeamFormingCfg, DPU_AoAProcDSP_Cmd_PrepareRangeAzimuthHeatMap, DPU_AoAProcDSP_Cmd_staticClutterCfg, DPU_AoAProcDSP_control(), DPU_CFAR_PEAK_GROUPING_DET_MATRIX_BASED, DPU_CFARCAProcDSP_Cmd_CfarDopplerCfg, DPU_CFARCAProcDSP_Cmd_CfarRangeCfg, DPU_CFARCAProcDSP_Cmd_FovDopplerCfg, DPU_CFARCAProcDSP_Cmd_FovRangeCfg, DPU_CFARCAProcDSP_control(), DPU_DopplerProcDSP_Cmd_staticClutterCfg, DPU_DopplerProcDSP_control(), DPU_RangeProcDSP_Cmd_dcRangeCfg, DPU_RangeProcDSP_control(), SubFrameObj_t::dpuAoAObj, SubFrameObj_t::dpuCFARCAObj, SubFrameObj_t::dpuCfg, SubFrameObj_t::dpuDopplerObj, SubFrameObj_t::dpuRangeObj, DPU_AoAProcDSP_Config_t::dynCfg, DPU_DopplerProcDSP_Config_t::dynCfg, SubFrameObj_t::dynCfg, ObjDetObj_t::edmaHandle, DPC_ObjectDetection_StaticClutterRemovalCfg_Base_t::enabled, DPC_ObjectDetection_DynCfg_t::extMaxVelCfg, DPC_ObjectDetection_DynCfg_t::fovAoaCfg, DPC_ObjectDetection_DynCfg_t::fovDoppler, DPC_ObjectDetection_DynCfg_t::fovRange, DPU_RangeProcDSP_Config_t::hwRes, ObjDetObj_t::interSubFrameProcToken, ObjDetObj_t::isCommonCfgReceived, DPU_AoAProc_StaticClutterRemovalCfg_t::isEnabled, DPU_DopplerProc_StaticClutterRemovalCfg_t::isEnabled, ObjDetObj_t::L3RamObj, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamTotal, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::L3RamUsage, DPU_CFARCAProc_FovCfg_t::max, DPC_ObjectDetection_PreStartCfg_t::memUsage, DPU_CFARCAProc_FovCfg_t::min, DPC_ObjectDetection_DynCfg_t::multiObjBeamFormingCfg, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, DPU_CFARCAProc_CfarCfg_t::peakGroupingScheme, DPC_ObjectDetection_RangeAzimuthHeatMapCfg_t::prepareRangeAzimuthHeatMap, DPC_ObjectDetection_DynCfg_t::prepareRangeAzimuthHeatMap, DPU_AoAProc_compRxChannelBiasCfg_t::rangeBias, DpuConfigs_t::rangeCfg, DPC_ObjectDetection_MemCfg_t::size, SubFrameObj_t::staticCfg, DPU_AoAProc_DynamicConfig_t::staticClutterCfg, DPU_DopplerProcDSP_DynamicConfig_t::staticClutterCfg, DPC_ObjectDetection_DynCfg_t::staticClutterRemovalCfg, ObjDetObj_t::stats, DPC_ObjectDetection_ExecuteResultExportedInfo_t::subFrameIdx, ObjDetObj_t::subFrameIndx, ObjDetObj_t::subFrameObj, DPC_ObjectDetection_Stats_t::subFramePreparationCycles, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapDPCUsed, DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapTotal, and DPC_ObjectDetection_DPC_IOCTL_preStartCfg_memUsage_t::SystemHeapUsed.
DPC_ObjectDetection_start()
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) start function which is invoked by the application using DPM_start API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 2029 of file objectdetection.c.
References ObjDetObj_t::commonCfg, DPC_ObjDetDSP_reconfigSubFrame(), DPC_ObjectDetection_Stats_t::frameStartIntCounter, ObjDetObj_t::isCommonCfgReceived, DPC_ObjectDetection_PreStartCommonCfg_t::numSubFrames, ObjDetObj_t::stats, and ObjDetObj_t::subFrameIndx.
DPC_ObjectDetection_stop()
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle) static
Description
DPC's (DPM registered) stop function which is invoked by the application using DPM_stop API.
Parameters
[in] handle DPM's DPC handle
Return values
Success - 0
Error - <0
Definition at line 2073 of file objectdetection.c.
References ObjDetObj_t::interSubFrameProcToken, and ObjDetObj_t::subFrameIndx.
Copyright 2024, Texas Instruments Incorporated