objectdetection/objdetdsp/src/objectdetection.c File Reference
objectdetection.c File Reference
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include <ti/drivers/soc/soc.h>
#include <ti/common/sys_common.h>
#include <ti/drivers/osal/DebugP.h>
#include <ti/drivers/osal/MemoryP.h>
#include <ti/drivers/edma/edma.h>
#include <ti/utils/mathutils/mathutils.h>
#include <ti/utils/cycleprofiler/cycle_profiler.h>
#include <ti/control/dpm/dpm.h>
#include <ti/board/antenna_geometry.h>
#include <ti/mathlib/mathlib.h>
#include <ti/datapath/dpc/objectdetection/objdetdsp/include/objectdetectioninternal.h>
#include <ti/datapath/dpc/objectdetection/objdetdsp/objectdetection.h>
#include <ti/alg/mmwavelib/mmwavelib.h>
Macros
#define DBG_DPC_OBJDET
#define DPC_OBJDET_RADAR_CUBE_DATABUF_BYTE_ALIGNMENT (sizeof(int16_t))
#define DPC_OBJDET_DET_MATRIX_DATABUF_BYTE_ALIGNMENT
#define DPC_OBJDET_CFAR_DET_LIST_BYTE_ALIGNMENT
#define DPC_OBJDET_POINT_CLOUD_CARTESIAN_BYTE_ALIGNMENT
#define DPC_OBJDET_POINT_CLOUD_SIDE_INFO_BYTE_ALIGNMENT
#define DPC_OBJDET_AZIMUTH_STATIC_HEAT_MAP_BYTE_ALIGNMENT
#define DPC_OBJDET_DET_OBJ_ELEVATION_ANGLE_BYTE_ALIGNMENT
#define DPC_OBJDET_MAX_NUM_OBJECTS 500U
#define DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE MMWAVELIB_WIN_BLACKMAN
#define DPC_DPU_DOPPLERPROC_FFT_WINDOW_TYPE MMWAVELIB_WIN_HANNING
#define DPC_OBJDET_QFORMAT_RANGE_FFT 15
#define DPC_OBJDET_QFORMAT_DOPPLER_FFT 19
Functions
static DPM_DPCHandle DPC_ObjectDetection_init (DPM_Handle dpmHandle, DPM_InitCfg *ptrInitCfg, int32_t *errCode)
static int32_t DPC_ObjectDetection_execute (DPM_DPCHandle handle, DPM_Buffer *ptrResult)
static int32_t DPC_ObjectDetection_ioctl (DPM_DPCHandle handle, uint32_t cmd, void *arg, uint32_t argLen)
static int32_t DPC_ObjectDetection_start (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_stop (DPM_DPCHandle handle)
static int32_t DPC_ObjectDetection_deinit (DPM_DPCHandle handle)
static void DPC_ObjectDetection_frameStart (DPM_DPCHandle handle)
void DPC_ObjectDetection_chirpEvent (DPM_DPCHandle handle)
static void DPC_ObjDetDSP_MemPoolReset (MemPoolObj *pool)
static void DPC_ObjDetDSP_MemPoolSet (MemPoolObj *pool, void *addr)
static void * DPC_ObjDetDSP_MemPoolGet (MemPoolObj *pool)
static uint32_t DPC_ObjDetDSP_MemPoolGetMaxUsage (MemPoolObj *pool)
static void * DPC_ObjDetDSP_MemPoolAlloc (MemPoolObj *pool, uint32_t size, uint8_t align)
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char *file, int32_t line)
static void DPC_ObjDetDSP_genWindow (void *win, uint32_t windowDatumType, uint32_t winLen, uint32_t winGenLen, int32_t oneQformat, uint32_t winType)
static uint32_t DPC_ObjDetDSP_GetRangeWinGenLen (uint16_t numAdcSamples)
static void DPC_ObjDetDSP_GenRangeWindow (DPU_RangeProcDSP_Config *rangeCfg)
static int32_t DPC_ObjDetDSP_rangeConfig (DPU_RangeProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, int16_t *window, uint32_t windowSize, cmplx16ImRe_t *twiddle, uint32_t twiddleSize, DPU_RangeProcDSP_Config *cfgSave)
static void DPC_ObjDetDSP_quadFit (float *x, float *y, float *xv, float *yv)
static void DPC_ObjDetDSP_rangeBiasRxChPhaseMeasure (DPC_ObjectDetection_StaticCfg *staticCfg, float targetDistance, float searchWinSize, uint16_t *detMatrix, uint32_t *symbolMatrix, DPU_AoAProc_compRxChannelBiasCfg *compRxChanCfg)
static uint32_t DPC_ObjDetDSP_GetDopplerWinGenLen (uint16_t numDopplerChirps)
static uint32_t DPC_ObjDetDSP_GenDopplerWindow (DPU_DopplerProcDSP_Config *cfg)
static void DPC_ObjDetDSP_GetRxChPhaseComp (DPC_ObjectDetection_StaticCfg *staticCfg, DPU_AoAProc_compRxChannelBiasCfg *inpCfg, DPU_AoAProc_compRxChannelBiasCfg *outCfg)
static int32_t DPC_ObjDetDSP_reconfigSubFrame (ObjDetObj *objDetObj, uint8_t subFrameIndx)
static int32_t DPC_ObjDetDSP_initDPU (ObjDetObj *objDetObj, uint8_t numSubFrames)
static int32_t DPC_ObjDetDSP_deinitDPU (ObjDetObj *objDetObj, uint8_t numSubFrames)
static int32_t DPC_ObjDetDSP_Config_MeasureRxChannelBiasCfg (ObjDetObj *obj, DPC_ObjectDetection_MeasureRxChannelBiasCfg *cfg)
static int32_t DPC_ObjDetDSP_dopplerConfig (DPU_DopplerProcDSP_Handle dpuHandle, DPC_ObjectDetection_StaticCfg *staticCfg, uint8_t log2NumDopplerBins, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_DetMatrix *detMatrix, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, int32_t *window, uint32_t windowSize, cmplx32ReIm_t *twiddleBuf, uint32_t twiddleSize, cmplx16ImRe_t *dftSinCosTable, uint32_t dftSinCosTableSize, DPU_DopplerProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_CFARCAconfig (DPU_CFARCAProcDSP_Handle dpuHandle, SubFrameObj *subFrameObj, EDMA_Handle edmaHandle, DPIF_DetMatrix *detMatrix, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, float rangeBias, DPU_CFARCAProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_AoAconfig (DPU_AoAProcDSP_Handle dpuHandle, DPU_AoAProc_compRxChannelBiasCfg *inpCommonCompRxCfg, DPC_ObjectDetection_StaticCfg *staticCfg, DPC_ObjectDetection_DynCfg *dynCfg, EDMA_Handle edmaHandle, DPIF_RadarCube *radarCube, DPIF_CFARDetList *cfarRngDopSnrList, uint32_t cfarRngDopSnrListSize, MemPoolObj *CoreL1RamObj, MemPoolObj *CoreL2RamObj, MemPoolObj *L3RamObj, int32_t *window, uint32_t windowSize, cmplx32ReIm_t *twiddleBuf, uint32_t twiddleSize, cmplx32ReIm_t *angleTwiddle32x32, uint32_t angleTwiddle32x32Size, DPU_AoAProcDSP_Config *cfgSave)
static int32_t DPC_ObjDetDSP_preStartConfig (SubFrameObj *subFrameObj, DPC_ObjectDetection_PreStartCommonCfg *commonCfg, DPC_ObjectDetection_PreStartCfg *preStartCfg, EDMA_Handle edmaHandle[EDMA_NUM_CC], MemPoolObj *L3ramObj, MemPoolObj *CoreL2RamObj, MemPoolObj *CoreL1RamObj, uint32_t *L3RamUsage, uint32_t *CoreL2RamUsage, uint32_t *CoreL1RamUsage)
Variables
ObjDetObj * gObjDetObj
DPM_ProcChainCfg gDPC_ObjectDetectionCfg
Global used to register Object Detection DPC in DPM.
Macro Definition Documentation
DBG_DPC_OBJDET
#define DBG_DPC_OBJDET
This is supplied at command line when application builds this file. This file is owned by the application and contains all resource partitioning, an application may include more than one DPC and also use resources outside of DPCs. The resource definitions used by this object detection DPC are prefixed by DPC_OBJDET_
Definition at line 80 of file objectdetection.c.
DPC_DPU_DOPPLERPROC_FFT_WINDOW_TYPE
#define DPC_DPU_DOPPLERPROC_FFT_WINDOW_TYPE MMWAVELIB_WIN_HANNING
Definition at line 179 of file objectdetection.c.
DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE
#define DPC_DPU_RANGEPROC_FFT_WINDOW_TYPE MMWAVELIB_WIN_BLACKMAN
Definition at line 178 of file objectdetection.c.
DPC_OBJDET_MAX_NUM_OBJECTS
#define DPC_OBJDET_MAX_NUM_OBJECTS 500U
Maximum Number of objects that can be detected in a frame
Definition at line 175 of file objectdetection.c.
DPC_OBJDET_QFORMAT_DOPPLER_FFT
#define DPC_OBJDET_QFORMAT_DOPPLER_FFT 19
Definition at line 183 of file objectdetection.c.
DPC_OBJDET_QFORMAT_RANGE_FFT
#define DPC_OBJDET_QFORMAT_RANGE_FFT 15
Definition at line 182 of file objectdetection.c.
Function Documentation
_DPC_Objdet_Assert()
void _DPC_Objdet_Assert (DPM_Handle handle, int32_t expression, const char * file, int32_t line)
Description
Sends Assert
Return values
Not Applicable.
Definition at line 337 of file objectdetection.c.
References DPM_DPCAssert_t::arg0, DPM_DPCAssert_t::arg1, DPM_CMD_DPC_ASSERT, DPM_ioctl(), DPM_MAX_FILE_NAME_LEN, DPM_DPCAssert_t::fileName, and DPM_DPCAssert_t::lineNum.
DPC_ObjDetDSP_genWindow()
static void DPC_ObjDetDSP_genWindow (void * win, uint32_t windowDatumType, uint32_t winLen, uint32_t winGenLen, int32_t oneQformat, uint32_t winType) inline static
Description
Inline function generates a single FFT window samples. It calls single precision sine and cosine functions from mathlib library for the first sample only, and then call mmwavelib_windowCoef_gen function to recursively generate cosine values for other samples.
Parameters
[out] win Pointer to calculated window samples.
[in] windowDatumType Window samples data format. For windowDatumType = MMWAVELIB_WINDOW_INT16, the samples format is int16_t. For windowDatumType = MMWAVELIB_WINDOW_INT32, the samples format is int32_t.
[in] winLen Nominal window length
[in] winGenLen Number of generated samples
[in] oneQformat Q format of samples.
[in] winType Type of window, one of MMWAVELIB_WIN_HANNING, MMWAVELIB_WIN_BLACKMAN, MMWAVELIB_WIN_RECT, or MMWAVELIB_WIN_HAMMING.
Return values
none.
Definition at line 376 of file objectdetection.c.
Referenced by DPC_ObjDetDSP_GenDopplerWindow(), and DPC_ObjDetDSP_GenRangeWindow().
Variable Documentation
gObjDetObj
ObjDetObj* gObjDetObj
Definition at line 83 of file objectdetection.c.
Referenced by DPC_ObjectDetection_init().
Copyright 2024, Texas Instruments Incorporated